---
- name: "Creates backend dir"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive  file"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Install Node Dep"
  shell: |
    cd ~/backend-app
    npm i

- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    cd ../
    npm install
    npm build
    sudo npm install forever -g
    sudo npm install ts-node -g
    forever start -c "ts-node -r tsconfig-paths/register -r dotevn/config src/main.ts" ./




  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
